// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TemperatureRPiApp.Models
{
    using System;
    using Newtonsoft.Json;

    public partial class TemperatureRestData
    {
        /// <summary>
        /// Initializes a new instance of the TemperatureRestData class.
        /// </summary>
        public TemperatureRestData() { }

        /// <summary>
        /// Initializes a new instance of the TemperatureRestData class.
        /// </summary>
        public TemperatureRestData(DateTime? date = default(DateTime?), double? temperature = default(double?), double? humidity = default(double?), int? location = default(int?))
        {
            Date = date;
            Temperature = temperature;
            Humidity = humidity;
            Location = location;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Temperature")]
        public double? Temperature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Humidity")]
        public double? Humidity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public int? Location { get; set; }

    }
}
